### PR TITLE
Fixed import of MWLayoutHelpers in INKDefaultsCell and INKAppIconView and duplicate symbols for ink_urlEncode

### PR DESCRIPTION
**Pull request by patrickkempff**
Fixed import of MWLayoutHelpers in INKAppIconView.m and INKDefaultsCell.m, 
Other files with this import are already fixed.

Also fixed compiler error: duplicate symbols for ink_urlEncode

### CODE REVIEW

**Comment by lazerwalker** [comment]
Ah, awesome. Thanks for this, and thanks also for the Travis fix!

**Comment by mtage70** [comment]
Hey @patrickkempff and/or @lazerwalker I'm getting linker command failures when using your pod in Cocoapods version 1.0.0, "duplicate symbol _ink_urlEncode". Might be an issue on my end but other pods appear to be working fine with the update. I'm using IntentKit/Maps and it was working fine on Cocoapods version 0.39.0. Let me know if you'll need any more info about this.

**Comment by lazerwalker** [comment]
@mtage70 this should be fixed on master, but a new version hasn't been released to Cocoapods yet. 

If you manually point the pod to master of this repo it should work, but I'm also hoping I'll have the time to cut a new proper Cocoapods release tomorrow (see #63)

**Comment by lazerwalker** [comment]
My current net access doesn't seem fast enough to want to let me push a new version to Cocoapods trunk, but if you try manually setting your Podfile to this git repo with a tag of `0.7.3`, that should work for you. Let me know!
